### ISSUE TITLE
How to revive the board

### ISSUE THREAD

**Issue by dizcza** [tuupola/axp192#34]
> Pay especially attention to DCDC1 which is usually used for powering the MCU. Your program disabling the power from the MCU upon boot basically bricks the board. Reviving the board from this situation is possible but might be difficult.

Well, had I read this line, I wouldn't have flashed the program. But I didn't read it. And flashed with the default config. And now I have almost a brick of an otherwise perfect M5Core2-AWS board. It's still seen in my PC as a `/dev/ttyUSB0` but I can flash no program anymore.

How to revive the board?
Thanks.

**Comment by dizcza** [comment]
The solution was to hold the reset button while flashing a program. I thought that I shorted the circuit because I heard a very strange noise when the flasher was connecting to the board, but in fact, I haven't shorted anything.

**Comment by tuupola** [comment]
Default config should be 3V0

https://github.com/tuupola/axp192/blob/master/Kconfig#L268

I revived mine by reflashing before the user program runs. One way to do it is to reboot the board and then immediately run the flashing program. If timing is correct if will reflash the board. I had to try this several times before it succeeded.

**Comment by tuupola** [comment]
Actually now I see when running a fresh `$ make menuconfig` all outputs are disabled by default. All outputs should be enabled by default. I maybe broke something recently. Will add correct default values to Kconfig.
